// QA-only evidence collector. Not an application test (Jest roots = src/).
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const root = '/home/moose/nextjs/CYBER_PHARMA/cyber-pharma-dev-v1-phase-3';
if (fs.realpathSync('.') !== root) throw Error('Wrong repository');
const qa = path.join(root, 'agent_docs/ACTIONS/RRM-001-CYBER-PHARMA/QA');
const out = path.join(qa, 'evidence'); fs.mkdirSync(out, { recursive: true });
const git = (...args) => cp.execFileSync('git', args, { encoding: 'utf8', maxBuffer: 20e6 });
const save = (name, data) => fs.writeFileSync(path.join(out, name), typeof data === 'string' ? data : JSON.stringify(data, null, 2) + '\n');
const sha = s => crypto.createHash('sha256').update(s).digest('hex');
const base = '5f45fb3db7ed0aa7d38dc6802c3a877c3f119dd9';
const eng = '4965c0c56ae7f658995d8b7cd634b5cdbc697f56';
const candidate = 'cad164d62a623a115541c0441302de01ff74da5b';
const identity = git('rev-parse', 'HEAD', 'refs/heads/qa/phase-3-rrm001');
if (identity.trim().split('\n').some(x => x !== candidate)) throw Error('Candidate drift');
save('preflight-identity.txt', identity + git('status', '--porcelain'));
save('engineering-to-candidate.diff', git('diff', '--no-ext-diff', '--binary', eng, candidate));
save('engineering-to-candidate.paths.txt', git('diff', '--name-status', eng, candidate));
save('baseline-to-candidate.paths.txt', git('diff', '--name-status', base, candidate));
save('pre-engineering.paths.txt', git('diff', '--name-status', base, '7b33756'));
save('implementation.paths.txt', git('diff', '--name-status', '7b33756', eng));
const preserved = ['src/proxy.ts','src/utils/supabase/middleware.ts','src/utils/supabase/actions.ts','src/app/api/auth/logout','src/app/api/auth/confirm','src/app/(auth)/layout.tsx','src/app/profile','src/app/(admin)','src/app/owedbook','src/services','src/mocks','src/components/owedbook','src/components/common','src/instrumentation.ts','supabase','scripts','package.json','package-lock.json','next.config.js'];
save('AC-301.diff', git('diff', base, candidate, '--', ...preserved));
save('AC-301-paths.json', preserved);
save('AC-302-tests.diff', git('diff', base, candidate, '--', 'src/__tests__'));
save('AC-303-nav.diff', git('diff', base, candidate, '--', 'src/components/global/Navbar.tsx','src/components/global/NavbarHome.tsx','src/components/global/MobileNav.tsx','src/components/global/UserMenu.tsx','src/app/(public)/HomePageContent.tsx'));
save('login-route.diff', git('diff', base, candidate, '--', 'src/app/api/auth/login/route.ts'));
const login = 'src/app/api/auth/login/route.ts';
const post = ref => git('show', ref + ':' + login).split('export async function POST')[1];
const tests = git('ls-tree','-r','--name-only',candidate,'src/__tests__').trim().split('\n').filter(p => /\/(Navbar\.invariant|InviteMemberForm|actions|proxy|MobileNav|UserMenu|owedbook|drawer-apply\.integration)\.test\.tsx?$/.test(p));
save('AC-302-named-suite-hashes.json', tests.map(p => ({path:p,baseline:sha(git('show',base+':'+p)),candidate:sha(git('show',candidate+':'+p)),working:sha(fs.readFileSync(p))})));
const deleted = git('diff','--name-only','--diff-filter=D').trim().split('\n').filter(Boolean);
save('preexisting-document-relocations.json', deleted.map(p => {const q='agent_docs/RESPONSES/_OLD/'+path.basename(p);return {original:p,relocated:q,byteEqual:fs.existsSync(q)&&Buffer.from(git('show','HEAD:'+p)).equals(fs.readFileSync(q))};}));
save('static-results.json', {postBytesEqual:post(base)===post(candidate),preservedDiffEmpty:git('diff',base,candidate,'--',...preserved)==='',engineeringToCandidateProductDiffEmpty:git('diff',eng,candidate,'--','src','supabase','scripts','package.json','package-lock.json','next.config.js','.env.example')==='',removedPaths:['src/app/moose-portal','src/app/api/auth/signup','src/components/auth/RegisterForm.tsx','src/components/auth/AuthTabs.tsx'].map(p=>({path:p,absent:!fs.existsSync(p)})),DA2Present:fs.existsSync(path.join(qa,'../evidence/DA-2_SUPABASE_SIGNUP_DISABLED.md'))});
const searches = [['action-source',['-n','getUserById|addMember|deleteUser|editUser|getUsers','src']],['signup-source',['-n','-i','sign ?up|register|create (an )?account','src']],['moose-source',['-n','-i','moose','README.md','docs','.env.example','src']],['flag-source',['-n','NEXT_PUBLIC_ENABLE_MOOSE_PORTAL','src','.env.example']],['admin-importers',['-n','utils/supabase/admin','src','scripts']],['removed-consumers',['-n','RegisterForm|AuthTabs|api/auth/signup|moose-portal/users/actions','src']]];
for (const [name,args] of searches) {const r=cp.spawnSync('rg',args,{encoding:'utf8'});save(name+'.txt','rg '+args.join(' ')+'\nexit='+r.status+'\n'+r.stdout+r.stderr);}
save('historical-action-ids.inherited.txt', fs.readFileSync(path.join(qa,'../evidence/S1_action_ids.txt')) .toString());
save('doctrine-history-search.txt', 'COMMAND: git log --all --name-only --pretty=format: -- agent_docs; case-insensitive filename filter\n'+git('log','--all','--name-only','--pretty=format:','--','agent_docs').split('\n').filter(p=>/qa.?playbook|ac.?sync|web_factory_p1_doctrine|patch.?kit/i.test(p)).join('\n')+'\n');
console.log('Static evidence preserved under QA/evidence; candidate pinned.');
