// Director-released SCRATCH-only build and interactive browser. No credentials in argv/logs.
const fs=require('fs'),path=require('path'),cp=require('child_process'),net=require('net'),crypto=require('crypto'),readline=require('readline');
const {chromium}=require('playwright'),dotenv=require('dotenv');
const root='/home/moose/nextjs/CYBER_PHARMA/cyber-pharma-dev-v1-phase-3',qa=__dirname,priorOut=path.join(qa,'evidence/SCRATCH'),out=process.argv.includes('--resume')?path.join(qa,'evidence/AC304_RESUME'):priorOut;
fs.mkdirSync(out,{recursive:true});
const save=(n,d)=>fs.writeFileSync(path.join(out,n),typeof d==='string'?d:JSON.stringify(d,null,2)+'\n');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...a)=>cp.execFileSync('git',a,{encoding:'utf8'}).trim();
const pin='cad164d62a623a115541c0441302de01ff74da5b';
if(fs.realpathSync('.')!==root||git('rev-parse','HEAD')!==pin||git('rev-parse','refs/heads/qa/phase-3-rrm001')!==pin)throw Error('Candidate mismatch');
if(git('diff',pin,'--','src','supabase','scripts','package.json','package-lock.json','next.config.js'))throw Error('Product drift');
const envBytes=fs.readFileSync(path.join(root,'.env.local')),cfg=dotenv.parse(envBytes);
const target=new URL(cfg.RLS_REPLICA_SUPABASE_URL),db=new URL(cfg.RLS_REPLICA_DB_URL),ref=target.hostname.split('.')[0];
const checks={configurationSource:'.env.local (read privately, never modified)',targetKey:'RLS_REPLICA_SUPABASE_URL',publishableKeySource:'RLS_REPLICA_PUBLISHABLE_KEY',secretKeySource:'RLS_REPLICA_SECRET_KEY',https:target.protocol==='https:',differentFromMainDev:cfg.RLS_REPLICA_SUPABASE_URL!==cfg.NEXT_PUBLIC_SUPABASE_URL,databaseProjectMatches:db.hostname.includes(ref)||decodeURIComponent(db.username).includes(ref),publishablePresent:!!cfg.RLS_REPLICA_PUBLISHABLE_KEY,secretPresent:!!cfg.RLS_REPLICA_SECRET_KEY,directorDesignatedConfiguredScratch:true,administrativeProjectLabelNotQueried:true};
save('target-verification.json',checks);
if(!checks.https||!checks.differentFromMainDev||!checks.databaseProjectMatches||!checks.publishablePresent||!checks.secretPresent)throw Error('SCRATCH mapping not verified');
const sensitive=Object.values(cfg).filter(v=>v.length>3).sort((a,b)=>b.length-a.length);
const redact=s=>sensitive.reduce((v,x)=>v.split(x).join('[REDACTED]'),String(s)).replace(/eyJ[A-Za-z0-9_.-]+/g,'[TOKEN REDACTED]');
const env={...process.env,NEXT_PUBLIC_SUPABASE_URL:cfg.RLS_REPLICA_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:cfg.RLS_REPLICA_PUBLISHABLE_KEY,SUPABASE_SECRET_KEY:cfg.RLS_REPLICA_SECRET_KEY,NEXT_PUBLIC_ENABLE_MOOSE_PORTAL:'',NEXT_PUBLIC_SITE_URL:'http://127.0.0.1:36055',NEXT_TELEMETRY_DISABLED:'1'};
const next=path.join(root,'.next');if(fs.existsSync(next)&&(fs.lstatSync(next).isSymbolicLink()||fs.realpathSync(next)!==next))throw Error('Unsafe generated path');
const reuse=process.argv.includes('--serve-existing');
if(reuse){const previous=JSON.parse(fs.readFileSync(path.join(priorOut,'server-identity.json')));if(fs.readFileSync(path.join(next,'BUILD_ID'),'utf8').trim()!==fs.readFileSync(path.join(priorOut,'BUILD_ID.txt'),'utf8').trim()||fs.readFileSync(path.join(next,'standalone/.next/BUILD_ID'),'utf8').trim()!==previous.buildId||hash(fs.readFileSync(path.join(next,'standalone/server.js')))!==previous.entrySha256)throw Error('Existing SCRATCH build identity/integrity mismatch');save('reuse-verification.json',{candidate:pin,buildId:previous.buildId,rootAndStandaloneIdMatch:true,standaloneEntryHashMatches:true,productDiffEmpty:true,rebuild:false});}
else{save('build-preflight.json',{candidate:pin,date:new Date().toISOString(),resolvedGeneratedPath:next,notSymlink:true,placeholderEvidencePreserved:['T','U','blank','board'].every(s=>fs.existsSync(path.join(qa,'evidence',s)))});fs.rmSync(next,{recursive:true,force:true});}
let server,browser,context,page,serverExited=false,serverLog='',port,base,buildId;const records=[];
async function stop(){if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});if(server&&!serverExited){server.kill('SIGTERM');for(let i=0;i<50&&!serverExited;i++)await new Promise(r=>setTimeout(r,100));if(!serverExited){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}}if(server){const free=await new Promise(resolve=>{const s=net.createServer();s.once('error',()=>resolve(false));s.listen(port,'127.0.0.1',()=>s.close(()=>resolve(true)));});save('server-stop.json',{pid:server.pid,exited:serverExited,port,portFree:free});}save('server-summary.json',{started:!!server,logSuppressedToAvoidAuthData:true,envFileBytesUnchanged:fs.readFileSync(path.join(root,'.env.local')).equals(envBytes)});}
async function openView(role,width,theme){if(context)await context.close();context=await browser.newContext({viewport:{width,height:900},colorScheme:theme});await context.addInitScript(t=>localStorage.setItem('theme',t),theme);await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==base&&u.origin!==target.origin)return route.abort();if(u.origin===target.origin&&/\/auth\/v1\/(signup|admin)|\/rest\/v1\//.test(u.pathname))return route.abort();return route.continue();});page=await context.newPage();await page.goto(base+'/auth');save('interactive-status.json',{stage:'awaiting-director-login',role,width,theme,origin:base,candidate:pin,buildId,credentialsRequestedInChat:false});console.log('READY '+role+' '+width+' '+theme+' — Director signs in only in the opened Chromium window.');}
async function captureWalk(role,width,theme){if(new URL(page.url()).pathname!=='/owedbook')throw Error('Login landing is not /owedbook; no credentials read');const record={role,width,theme,loginLanding:'/owedbook',candidate:pin};if(role==='ADMIN'){await page.goto(base+'/admin-portal');record.adminPath=new URL(page.url()).pathname;}await page.goto(base+'/profile');record.profilePath=new URL(page.url()).pathname;record.roleBadgeVisible=await page.getByText(role==='ADMIN'?'Admin':'Member',{exact:true}).count()>0;record.passwordForm=(await page.locator('input[type=password]').count())===2;const shot=role+'-'+width+'-'+theme+'-profile.png';await page.screenshot({path:path.join(out,shot),fullPage:true,mask:[page.locator('input'),page.locator('header'),page.locator('p').filter({hasText:/@/}),page.locator('p.text-xl')]});record.screenshot=shot;
 if(width===375){const menu=page.getByRole('button',{name:/open menu/i});if(await menu.count())await menu.click();}
 let logout=page.getByRole('button',{name:/^log\s*out$/i});if(await logout.count()&&await logout.first().isVisible())await logout.first().click();else{const trigger=page.locator('[data-slot="dropdown-menu-trigger"],button[aria-haspopup="menu"]').last();await trigger.click();await page.getByRole('menuitem',{name:/logout|log out/i}).click();}
 await page.waitForTimeout(1500);record.logoutLanding=new URL(page.url()).pathname;record.expectedLogoutLanding='/';record.homepageDestinationRulingPending=true;await page.goto(base+'/owedbook');record.unauthenticatedOwedbookLanding=new URL(page.url()).pathname;record.remainingSupabaseAuthCookieCount=(await context.cookies()).filter(c=>/^sb-.*auth-token/.test(c.name)&&c.value).length;record.sessionEnded=record.unauthenticatedOwedbookLanding==='/auth'&&record.remainingSupabaseAuthCookieCount===0;records.push(record);save('walk-results.json',records);console.log('Recorded '+role+' '+width+' '+theme+'; logout pathname '+record.logoutLanding+'; session ended='+record.sessionEnded);}
async function main(){
 if(!reuse){console.log('Verified configured SCRATCH mapping; building candidate with private in-memory configuration.');
 const result=await new Promise(resolve=>{let log='';const child=cp.spawn(path.join(root,'node_modules/.bin/next'),['build'],{cwd:root,env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);child.on('close',exit=>resolve({exit,log}));});save('build.log',redact(result.log));save('build-result.json',{exit:result.exit,candidate:pin,routes:result.log.split('\n').filter(l=>/^[┌├└]/.test(l.trim()))});if(result.exit!==0)throw Error('SCRATCH build failed (redacted log preserved)');
 }
 buildId=fs.readFileSync(path.join(next,'BUILD_ID'),'utf8').trim();save('BUILD_ID.txt',buildId+'\n');if(!reuse){fs.cpSync(path.join(root,'public'),path.join(next,'standalone/public'),{recursive:true});fs.cpSync(path.join(next,'static'),path.join(next,'standalone/.next/static'),{recursive:true});}
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(d,x.name)):[path.join(d,x.name)]);const js=walk(path.join(next,'static')).filter(p=>p.endsWith('.js')).map(p=>fs.readFileSync(p,'utf8'));const binding={clientBundleContainsScratchUrl:js.some(s=>s.includes(cfg.RLS_REPLICA_SUPABASE_URL)),clientBundleContainsMainDevUrl:js.some(s=>s.includes(cfg.NEXT_PUBLIC_SUPABASE_URL)),clientBundleContainsScratchSecret:js.some(s=>s.includes(cfg.RLS_REPLICA_SECRET_KEY))};save('bundle-target-verification.json',binding);if(!binding.clientBundleContainsScratchUrl||binding.clientBundleContainsMainDevUrl||binding.clientBundleContainsScratchSecret)throw Error('Built target binding failed');
 port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});base='http://127.0.0.1:'+port;
 server=cp.spawn(process.execPath,[path.join(next,'standalone/server.js')],{cwd:root,env:{...env,PORT:String(port),HOSTNAME:'127.0.0.1'},stdio:['ignore','pipe','pipe']});server.on('exit',()=>serverExited=true);server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
 let ready=false;for(let i=0;i<100&&!serverExited;i++){try{if((await fetch(base+'/auth')).status===200){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,200));}if(!ready)throw Error('Standalone boot failed; no fallback');save('server-identity.json',{candidate:pin,buildId,standaloneBuildId:fs.readFileSync(path.join(next,'standalone/.next/BUILD_ID'),'utf8').trim(),pid:server.pid,origin:base,port,entry:path.join(next,'standalone/server.js'),entrySha256:hash(fs.readFileSync(path.join(next,'standalone/server.js'))),target:'configured SCRATCH; values withheld'});
 try{browser=await chromium.launch({headless:false});}catch{save('browser-access.json',{headfulLaunchSucceeded:false,missing:'Usable graphical Chromium display for Director interactive credentials'});throw Error('Interactive browser launch unavailable');}
 save('browser-access.json',{headfulLaunchSucceeded:true,directorVisibilityConfirmed:false});await openView('ADMIN',1440,'light');
 const rl=readline.createInterface({input:process.stdin});for await(const line of rl){const [cmd,role,width,theme]=line.trim().split(' ');if(cmd==='stop'){rl.close();break;}if(cmd==='status'){console.log(JSON.stringify({pathname:new URL(page.url()).pathname,windowOpen:!page.isClosed(),completed:records.length}));continue;}if(cmd==='visible'){save('browser-access.json',{headfulLaunchSucceeded:true,directorVisibilityConfirmed:true});continue;}if(cmd==='open'&&['ADMIN','MEMBER'].includes(role)&&['1440','375'].includes(width)&&['light','dark'].includes(theme))await openView(role,Number(width),theme);else if(cmd==='record'&&['ADMIN','MEMBER'].includes(role)&&['1440','375'].includes(width)&&['light','dark'].includes(theme)){try{await captureWalk(role,Number(width),theme);}catch{save('walk-boundary.json',{role,width,theme,message:'Journey not complete at requested checkpoint; inspect browser without logging credentials'});console.log('Walk checkpoint incomplete; see browser.');}}}
}
main().catch(e=>{save('blocked.json',{message:redact(e.message)});console.log('SCRATCH checkpoint: '+redact(e.message));process.exitCode=1;}).finally(stop);
